const FOOD_RULES = [
  {
    key: "milk",
    displayName: "Milk",
    aliases: ["milk", "whole milk", "2% milk", "skim milk"],
    defaultCategory: "Dairy",
    shelfLife: { fridgeDays: 7 },
    expiringSoonDays: 2,
    source: "USDA/FoodKeeper",
  },
  {
    key: "eggs",
    displayName: "Eggs",
    aliases: ["eggs", "large eggs", "brown eggs"],
    defaultCategory: "Dairy",
    shelfLife: { fridgeDays: 21 },
    expiringSoonDays: 4,
    source: "USDA/FoodKeeper",
  },
  {
    key: "juice",
    displayName: "Juice",
    aliases: ["juice", "orange juice", "apple juice", "grape juice"],
    defaultCategory: "Beverages",
    shelfLife: { fridgeDays: 7, pantryDays: 30 },
    expiringSoonDays: 2,
    source: "USDA/FoodKeeper",
  },
  {
    key: "bread",
    displayName: "Bread",
    aliases: ["bread", "white bread", "wheat bread", "toast bread"],
    defaultCategory: "Bakery",
    shelfLife: { pantryDays: 7, freezerDays: 90 },
    expiringSoonDays: 2,
    source: "USDA/FoodKeeper",
  },
  {
    key: "chicken",
    displayName: "Chicken",
    aliases: ["chicken breast", "raw chicken", "chicken thighs", "chicken"],
    defaultCategory: "Meat",
    shelfLife: { fridgeDays: 2, freezerDays: 270 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  {
    key: "fish",
    displayName: "Fish",
    aliases: ["fish", "salmon", "tilapia", "cod"],
    defaultCategory: "Seafood",
    shelfLife: { fridgeDays: 2, freezerDays: 90 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  {
    key: "strawberries",
    displayName: "Strawberries",
    aliases: ["strawberries", "strawberry"],
    defaultCategory: "Fruits",
    shelfLife: { fridgeDays: 5, freezerDays: 180 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  {
    key: "spinach",
    displayName: "Spinach",
    aliases: ["spinach"],
    defaultCategory: "Vegetables",
    shelfLife: { fridgeDays: 5, freezerDays: 300 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  {
    key: "chips",
    displayName: "Chips",
    aliases: ["chips", "potato chips", "tortilla chips"],
    defaultCategory: "Snacks",
    shelfLife: { pantryDays: 30 },
    expiringSoonDays: 5,
    source: "USDA/FoodKeeper",
  },
  {
    key: "frozen-pizza",
    displayName: "Frozen Pizza",
    aliases: ["frozen pizza", "pizza"],
    defaultCategory: "Frozen",
    shelfLife: { freezerDays: 60 },
    expiringSoonDays: 7,
    source: "USDA/FoodKeeper",
  },
];

const CATEGORY_FALLBACK_RULES = {
  bakery: {
    key: "fallback-bakery",
    displayName: "Bakery",
    aliases: [],
    defaultCategory: "Bakery",
    shelfLife: { pantryDays: 7, freezerDays: 90 },
    expiringSoonDays: 2,
    source: "USDA/FoodKeeper",
  },
  beverages: {
    key: "fallback-beverages",
    displayName: "Beverages",
    aliases: [],
    defaultCategory: "Beverages",
    shelfLife: { fridgeDays: 7, pantryDays: 30 },
    expiringSoonDays: 2,
    source: "USDA/FoodKeeper",
  },
  condiments: {
    key: "fallback-condiments",
    displayName: "Condiments",
    aliases: [],
    defaultCategory: "Condiments",
    shelfLife: { fridgeDays: 30, pantryDays: 90 },
    expiringSoonDays: 5,
    source: "USDA/FoodKeeper",
  },
  dairy: {
    key: "fallback-dairy",
    displayName: "Dairy",
    aliases: [],
    defaultCategory: "Dairy",
    shelfLife: { fridgeDays: 7, freezerDays: 30 },
    expiringSoonDays: 2,
    source: "USDA/FoodKeeper",
  },
  frozen: {
    key: "fallback-frozen",
    displayName: "Frozen",
    aliases: [],
    defaultCategory: "Frozen",
    shelfLife: { freezerDays: 90 },
    expiringSoonDays: 7,
    source: "USDA/FoodKeeper",
  },
  fruits: {
    key: "fallback-fruits",
    displayName: "Fruits",
    aliases: [],
    defaultCategory: "Fruits",
    shelfLife: { fridgeDays: 5, pantryDays: 5, freezerDays: 180 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  meat: {
    key: "fallback-meat",
    displayName: "Meat",
    aliases: [],
    defaultCategory: "Meat",
    shelfLife: { fridgeDays: 2, freezerDays: 120 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  pantry: {
    key: "fallback-pantry",
    displayName: "Pantry",
    aliases: [],
    defaultCategory: "Pantry",
    shelfLife: { pantryDays: 30 },
    expiringSoonDays: 5,
    source: "USDA/FoodKeeper",
  },
  seafood: {
    key: "fallback-seafood",
    displayName: "Seafood",
    aliases: [],
    defaultCategory: "Seafood",
    shelfLife: { fridgeDays: 2, freezerDays: 90 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
  snacks: {
    key: "fallback-snacks",
    displayName: "Snacks",
    aliases: [],
    defaultCategory: "Snacks",
    shelfLife: { pantryDays: 30 },
    expiringSoonDays: 5,
    source: "USDA/FoodKeeper",
  },
  misc: {
    key: "fallback-misc",
    displayName: "Misc",
    aliases: [],
    defaultCategory: "Misc",
    shelfLife: { pantryDays: 14, fridgeDays: 7 },
    expiringSoonDays: 3,
    source: "USDA/FoodKeeper",
  },
  vegetables: {
    key: "fallback-vegetables",
    displayName: "Vegetables",
    aliases: [],
    defaultCategory: "Vegetables",
    shelfLife: { fridgeDays: 5, freezerDays: 180 },
    expiringSoonDays: 1,
    source: "USDA/FoodKeeper",
  },
};

module.exports = {
  FOOD_RULES,
  CATEGORY_FALLBACK_RULES,
};